#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[System.Data.Linq.Mapping.DatabaseAttribute(Name="chat")]
public partial class chatDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Inserttblog(tblog instance);
  partial void Updatetblog(tblog instance);
  partial void Deletetblog(tblog instance);
  partial void Inserttbmsg(tbmsg instance);
  partial void Updatetbmsg(tbmsg instance);
  partial void Deletetbmsg(tbmsg instance);
  partial void Inserttbrom(tbrom instance);
  partial void Updatetbrom(tbrom instance);
  partial void Deletetbrom(tbrom instance);
  partial void Inserttbuser(tbuser instance);
  partial void Updatetbuser(tbuser instance);
  partial void Deletetbuser(tbuser instance);
  #endregion
	
	public chatDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["chatConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public chatDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public chatDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public chatDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public chatDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tblog> tblogs
	{
		get
		{
			return this.GetTable<tblog>();
		}
	}
	
	public System.Data.Linq.Table<tbmsg> tbmsgs
	{
		get
		{
			return this.GetTable<tbmsg>();
		}
	}
	
	public System.Data.Linq.Table<tbrom> tbroms
	{
		get
		{
			return this.GetTable<tbrom>();
		}
	}
	
	public System.Data.Linq.Table<tbuser> tbusers
	{
		get
		{
			return this.GetTable<tbuser>();
		}
	}
}

[Table(Name="dbo.tblog")]
public partial class tblog : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _logcod;
	
	private System.Nullable<int> _logusrcod;
	
	private System.Nullable<int> _logromcod;
	
	private EntityRef<tbrom> _tbrom;
	
	private EntityRef<tbuser> _tbuser;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnlogcodChanging(int value);
    partial void OnlogcodChanged();
    partial void OnlogusrcodChanging(System.Nullable<int> value);
    partial void OnlogusrcodChanged();
    partial void OnlogromcodChanging(System.Nullable<int> value);
    partial void OnlogromcodChanged();
    #endregion
	
	public tblog()
	{
		this._tbrom = default(EntityRef<tbrom>);
		this._tbuser = default(EntityRef<tbuser>);
		OnCreated();
	}
	
	[Column(Storage="_logcod", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int logcod
	{
		get
		{
			return this._logcod;
		}
		set
		{
			if ((this._logcod != value))
			{
				if (this._tbuser.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnlogcodChanging(value);
				this.SendPropertyChanging();
				this._logcod = value;
				this.SendPropertyChanged("logcod");
				this.OnlogcodChanged();
			}
		}
	}
	
	[Column(Storage="_logusrcod", DbType="Int")]
	public System.Nullable<int> logusrcod
	{
		get
		{
			return this._logusrcod;
		}
		set
		{
			if ((this._logusrcod != value))
			{
				this.OnlogusrcodChanging(value);
				this.SendPropertyChanging();
				this._logusrcod = value;
				this.SendPropertyChanged("logusrcod");
				this.OnlogusrcodChanged();
			}
		}
	}
	
	[Column(Storage="_logromcod", DbType="Int")]
	public System.Nullable<int> logromcod
	{
		get
		{
			return this._logromcod;
		}
		set
		{
			if ((this._logromcod != value))
			{
				if (this._tbrom.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnlogromcodChanging(value);
				this.SendPropertyChanging();
				this._logromcod = value;
				this.SendPropertyChanged("logromcod");
				this.OnlogromcodChanged();
			}
		}
	}
	
	[Association(Name="tbrom_tblog", Storage="_tbrom", ThisKey="logromcod", IsForeignKey=true)]
	public tbrom tbrom
	{
		get
		{
			return this._tbrom.Entity;
		}
		set
		{
			tbrom previousValue = this._tbrom.Entity;
			if (((previousValue != value) 
						|| (this._tbrom.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tbrom.Entity = null;
					previousValue.tblogs.Remove(this);
				}
				this._tbrom.Entity = value;
				if ((value != null))
				{
					value.tblogs.Add(this);
					this._logromcod = value.romcod;
				}
				else
				{
					this._logromcod = default(Nullable<int>);
				}
				this.SendPropertyChanged("tbrom");
			}
		}
	}
	
	[Association(Name="tbuser_tblog", Storage="_tbuser", ThisKey="logcod", IsForeignKey=true)]
	public tbuser tbuser
	{
		get
		{
			return this._tbuser.Entity;
		}
		set
		{
			tbuser previousValue = this._tbuser.Entity;
			if (((previousValue != value) 
						|| (this._tbuser.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tbuser.Entity = null;
					previousValue.tblog = null;
				}
				this._tbuser.Entity = value;
				if ((value != null))
				{
					value.tblog = this;
					this._logcod = value.usrcod;
				}
				else
				{
					this._logcod = default(int);
				}
				this.SendPropertyChanged("tbuser");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[Table(Name="dbo.tbmsg")]
public partial class tbmsg : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _msgcod;
	
	private string _msgdsc;
	
	private System.Nullable<System.DateTime> _msgdat;
	
	private System.Nullable<int> _msgfrmusr;
	
	private System.Nullable<int> _msgtousrcod;
	
	private System.Nullable<int> _msgromcod;
	
	private EntityRef<tbrom> _tbrom;
	
	private EntityRef<tbuser> _tbuser;
	
	private EntityRef<tbuser> _tbuser1;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmsgcodChanging(int value);
    partial void OnmsgcodChanged();
    partial void OnmsgdscChanging(string value);
    partial void OnmsgdscChanged();
    partial void OnmsgdatChanging(System.Nullable<System.DateTime> value);
    partial void OnmsgdatChanged();
    partial void OnmsgfrmusrChanging(System.Nullable<int> value);
    partial void OnmsgfrmusrChanged();
    partial void OnmsgtousrcodChanging(System.Nullable<int> value);
    partial void OnmsgtousrcodChanged();
    partial void OnmsgromcodChanging(System.Nullable<int> value);
    partial void OnmsgromcodChanged();
    #endregion
	
	public tbmsg()
	{
		this._tbrom = default(EntityRef<tbrom>);
		this._tbuser = default(EntityRef<tbuser>);
		this._tbuser1 = default(EntityRef<tbuser>);
		OnCreated();
	}
	
	[Column(Storage="_msgcod", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int msgcod
	{
		get
		{
			return this._msgcod;
		}
		set
		{
			if ((this._msgcod != value))
			{
				this.OnmsgcodChanging(value);
				this.SendPropertyChanging();
				this._msgcod = value;
				this.SendPropertyChanged("msgcod");
				this.OnmsgcodChanged();
			}
		}
	}
	
	[Column(Storage="_msgdsc", DbType="VarChar(50)")]
	public string msgdsc
	{
		get
		{
			return this._msgdsc;
		}
		set
		{
			if ((this._msgdsc != value))
			{
				this.OnmsgdscChanging(value);
				this.SendPropertyChanging();
				this._msgdsc = value;
				this.SendPropertyChanged("msgdsc");
				this.OnmsgdscChanged();
			}
		}
	}
	
	[Column(Storage="_msgdat", DbType="DateTime")]
	public System.Nullable<System.DateTime> msgdat
	{
		get
		{
			return this._msgdat;
		}
		set
		{
			if ((this._msgdat != value))
			{
				this.OnmsgdatChanging(value);
				this.SendPropertyChanging();
				this._msgdat = value;
				this.SendPropertyChanged("msgdat");
				this.OnmsgdatChanged();
			}
		}
	}
	
	[Column(Storage="_msgfrmusr", DbType="Int")]
	public System.Nullable<int> msgfrmusr
	{
		get
		{
			return this._msgfrmusr;
		}
		set
		{
			if ((this._msgfrmusr != value))
			{
				if (this._tbuser.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnmsgfrmusrChanging(value);
				this.SendPropertyChanging();
				this._msgfrmusr = value;
				this.SendPropertyChanged("msgfrmusr");
				this.OnmsgfrmusrChanged();
			}
		}
	}
	
	[Column(Storage="_msgtousrcod", DbType="Int")]
	public System.Nullable<int> msgtousrcod
	{
		get
		{
			return this._msgtousrcod;
		}
		set
		{
			if ((this._msgtousrcod != value))
			{
				if (this._tbuser1.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnmsgtousrcodChanging(value);
				this.SendPropertyChanging();
				this._msgtousrcod = value;
				this.SendPropertyChanged("msgtousrcod");
				this.OnmsgtousrcodChanged();
			}
		}
	}
	
	[Column(Storage="_msgromcod", DbType="Int")]
	public System.Nullable<int> msgromcod
	{
		get
		{
			return this._msgromcod;
		}
		set
		{
			if ((this._msgromcod != value))
			{
				if (this._tbrom.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnmsgromcodChanging(value);
				this.SendPropertyChanging();
				this._msgromcod = value;
				this.SendPropertyChanged("msgromcod");
				this.OnmsgromcodChanged();
			}
		}
	}
	
	[Association(Name="tbrom_tbmsg", Storage="_tbrom", ThisKey="msgromcod", IsForeignKey=true)]
	public tbrom tbrom
	{
		get
		{
			return this._tbrom.Entity;
		}
		set
		{
			tbrom previousValue = this._tbrom.Entity;
			if (((previousValue != value) 
						|| (this._tbrom.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tbrom.Entity = null;
					previousValue.tbmsgs.Remove(this);
				}
				this._tbrom.Entity = value;
				if ((value != null))
				{
					value.tbmsgs.Add(this);
					this._msgromcod = value.romcod;
				}
				else
				{
					this._msgromcod = default(Nullable<int>);
				}
				this.SendPropertyChanged("tbrom");
			}
		}
	}
	
	[Association(Name="tbuser_tbmsg", Storage="_tbuser", ThisKey="msgfrmusr", IsForeignKey=true)]
	public tbuser tbuser
	{
		get
		{
			return this._tbuser.Entity;
		}
		set
		{
			tbuser previousValue = this._tbuser.Entity;
			if (((previousValue != value) 
						|| (this._tbuser.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tbuser.Entity = null;
					previousValue.tbmsgs.Remove(this);
				}
				this._tbuser.Entity = value;
				if ((value != null))
				{
					value.tbmsgs.Add(this);
					this._msgfrmusr = value.usrcod;
				}
				else
				{
					this._msgfrmusr = default(Nullable<int>);
				}
				this.SendPropertyChanged("tbuser");
			}
		}
	}
	
	[Association(Name="tbuser_tbmsg1", Storage="_tbuser1", ThisKey="msgtousrcod", IsForeignKey=true)]
	public tbuser tbuser1
	{
		get
		{
			return this._tbuser1.Entity;
		}
		set
		{
			tbuser previousValue = this._tbuser1.Entity;
			if (((previousValue != value) 
						|| (this._tbuser1.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tbuser1.Entity = null;
					previousValue.tbmsgs1.Remove(this);
				}
				this._tbuser1.Entity = value;
				if ((value != null))
				{
					value.tbmsgs1.Add(this);
					this._msgtousrcod = value.usrcod;
				}
				else
				{
					this._msgtousrcod = default(Nullable<int>);
				}
				this.SendPropertyChanged("tbuser1");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[Table(Name="dbo.tbrom")]
public partial class tbrom : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _romcod;
	
	private string _romnam;
	
	private EntitySet<tblog> _tblogs;
	
	private EntitySet<tbmsg> _tbmsgs;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnromcodChanging(int value);
    partial void OnromcodChanged();
    partial void OnromnamChanging(string value);
    partial void OnromnamChanged();
    #endregion
	
	public tbrom()
	{
		this._tblogs = new EntitySet<tblog>(new Action<tblog>(this.attach_tblogs), new Action<tblog>(this.detach_tblogs));
		this._tbmsgs = new EntitySet<tbmsg>(new Action<tbmsg>(this.attach_tbmsgs), new Action<tbmsg>(this.detach_tbmsgs));
		OnCreated();
	}
	
	[Column(Storage="_romcod", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int romcod
	{
		get
		{
			return this._romcod;
		}
		set
		{
			if ((this._romcod != value))
			{
				this.OnromcodChanging(value);
				this.SendPropertyChanging();
				this._romcod = value;
				this.SendPropertyChanged("romcod");
				this.OnromcodChanged();
			}
		}
	}
	
	[Column(Storage="_romnam", DbType="VarChar(50)")]
	public string romnam
	{
		get
		{
			return this._romnam;
		}
		set
		{
			if ((this._romnam != value))
			{
				this.OnromnamChanging(value);
				this.SendPropertyChanging();
				this._romnam = value;
				this.SendPropertyChanged("romnam");
				this.OnromnamChanged();
			}
		}
	}
	
	[Association(Name="tbrom_tblog", Storage="_tblogs", OtherKey="logromcod")]
	public EntitySet<tblog> tblogs
	{
		get
		{
			return this._tblogs;
		}
		set
		{
			this._tblogs.Assign(value);
		}
	}
	
	[Association(Name="tbrom_tbmsg", Storage="_tbmsgs", OtherKey="msgromcod")]
	public EntitySet<tbmsg> tbmsgs
	{
		get
		{
			return this._tbmsgs;
		}
		set
		{
			this._tbmsgs.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tblogs(tblog entity)
	{
		this.SendPropertyChanging();
		entity.tbrom = this;
	}
	
	private void detach_tblogs(tblog entity)
	{
		this.SendPropertyChanging();
		entity.tbrom = null;
	}
	
	private void attach_tbmsgs(tbmsg entity)
	{
		this.SendPropertyChanging();
		entity.tbrom = this;
	}
	
	private void detach_tbmsgs(tbmsg entity)
	{
		this.SendPropertyChanging();
		entity.tbrom = null;
	}
}

[Table(Name="dbo.tbuser")]
public partial class tbuser : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _usrcod;
	
	private string _usrname;
	
	private string _usrpass;
	
	private EntityRef<tblog> _tblog;
	
	private EntitySet<tbmsg> _tbmsgs;
	
	private EntitySet<tbmsg> _tbmsgs1;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnusrcodChanging(int value);
    partial void OnusrcodChanged();
    partial void OnusrnameChanging(string value);
    partial void OnusrnameChanged();
    partial void OnusrpassChanging(string value);
    partial void OnusrpassChanged();
    #endregion
	
	public tbuser()
	{
		this._tblog = default(EntityRef<tblog>);
		this._tbmsgs = new EntitySet<tbmsg>(new Action<tbmsg>(this.attach_tbmsgs), new Action<tbmsg>(this.detach_tbmsgs));
		this._tbmsgs1 = new EntitySet<tbmsg>(new Action<tbmsg>(this.attach_tbmsgs1), new Action<tbmsg>(this.detach_tbmsgs1));
		OnCreated();
	}
	
	[Column(Storage="_usrcod", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int usrcod
	{
		get
		{
			return this._usrcod;
		}
		set
		{
			if ((this._usrcod != value))
			{
				this.OnusrcodChanging(value);
				this.SendPropertyChanging();
				this._usrcod = value;
				this.SendPropertyChanged("usrcod");
				this.OnusrcodChanged();
			}
		}
	}
	
	[Column(Storage="_usrname", DbType="VarChar(50)")]
	public string usrname
	{
		get
		{
			return this._usrname;
		}
		set
		{
			if ((this._usrname != value))
			{
				this.OnusrnameChanging(value);
				this.SendPropertyChanging();
				this._usrname = value;
				this.SendPropertyChanged("usrname");
				this.OnusrnameChanged();
			}
		}
	}
	
	[Column(Storage="_usrpass", DbType="VarChar(50)")]
	public string usrpass
	{
		get
		{
			return this._usrpass;
		}
		set
		{
			if ((this._usrpass != value))
			{
				this.OnusrpassChanging(value);
				this.SendPropertyChanging();
				this._usrpass = value;
				this.SendPropertyChanged("usrpass");
				this.OnusrpassChanged();
			}
		}
	}
	
	[Association(Name="tbuser_tblog", Storage="_tblog", ThisKey="usrcod", IsUnique=true, IsForeignKey=false)]
	public tblog tblog
	{
		get
		{
			return this._tblog.Entity;
		}
		set
		{
			tblog previousValue = this._tblog.Entity;
			if (((previousValue != value) 
						|| (this._tblog.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblog.Entity = null;
					previousValue.tbuser = null;
				}
				this._tblog.Entity = value;
				if ((value != null))
				{
					value.tbuser = this;
				}
				this.SendPropertyChanged("tblog");
			}
		}
	}
	
	[Association(Name="tbuser_tbmsg", Storage="_tbmsgs", OtherKey="msgfrmusr")]
	public EntitySet<tbmsg> tbmsgs
	{
		get
		{
			return this._tbmsgs;
		}
		set
		{
			this._tbmsgs.Assign(value);
		}
	}
	
	[Association(Name="tbuser_tbmsg1", Storage="_tbmsgs1", OtherKey="msgtousrcod")]
	public EntitySet<tbmsg> tbmsgs1
	{
		get
		{
			return this._tbmsgs1;
		}
		set
		{
			this._tbmsgs1.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tbmsgs(tbmsg entity)
	{
		this.SendPropertyChanging();
		entity.tbuser = this;
	}
	
	private void detach_tbmsgs(tbmsg entity)
	{
		this.SendPropertyChanging();
		entity.tbuser = null;
	}
	
	private void attach_tbmsgs1(tbmsg entity)
	{
		this.SendPropertyChanging();
		entity.tbuser1 = this;
	}
	
	private void detach_tbmsgs1(tbmsg entity)
	{
		this.SendPropertyChanging();
		entity.tbuser1 = null;
	}
}
#pragma warning restore 1591
